### ISSUE TITLE
Parallels 15 라는 가상머신에서 크래쉬가 일어납니다.

### ISSUE THREAD

**Issue by mingkyme** [Hoon-Dev/StickerTodo#1]
![스크린샷 2020-09-28 오전 9 26 03](https://user-images.githubusercontent.com/45954551/94379655-c9e11800-016c-11eb-86b0-43472c50ef9e.png)

**Comment by Hoon-Dev** [comment]
가상머신에 설치된 윈도우를 업데이트하여 진행해주세요. !
